Private Event App
AhmedTohamy01/Microverse-Private-Events pull request #1
Opened 2020-08-25 21:22 UTC by AhmedTohamy01

Private Event App includes:

1) User Model & Controller & Views.
2) Event Model & Controller & Views.
3) Attendee Model & Controller & Views.
4) Sign-up & Sign-in Functionality. 
5) Show events in the user's page.

2020-09-02 18:47 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 


#### Behaviour

* [ ] It has functional `login` page (authentication WITHOUT password, just providing a user email) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] Logged in user can create new event  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] Event's index page displays past and upcoming events lists  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] The event's show page displays the list of attendants  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] Let's activate linter checks for this project
- [ ] Lets kindly remove the `README` title in the readme.MD file.
- [ ] Let define routes for each component in the app. 
- [ ] The events table should have a creator_id as the foreign key ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
#### Project specific

#### Database foreign keys and indexes ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/foreign_key_index_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

* [ ] the events table has column `creator_id` of type `integer`
* [ ] an index for `creator_id` column is added
* [ ] an index for `event_id` column is added
* [ ] an index for `user_id` column is added
#### Tests
- Kindly use Rspec and capybara to test your project.
* [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
-  Checks comments below
Note: Am aware that you have implemented some app behaviours, however, once you have defined the routes you can use it as a checklist for the project. 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-02 18:47 UTC, kobiyoyo commented on app/models/event.rb
> +  scope :past_events, -> { where('date < ? ', Date.today) }
Lets use `Time.zone.now`,because you will want to put into consideration the time of events also.

2020-09-02 18:47 UTC, kobiyoyo commented on app/models/user.rb
> +  has_many :event, class_name: 'Event', foreign_key: 'user_id'
Here you should create a foreign_key with `creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-09-02 18:47 UTC, kobiyoyo commented on app/models/event.rb
> +  belongs_to :user
Event model should `belongs_to` creator and have a  class_name: "User" ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-09-02 18:47 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +  end
##### UsersController

###### `show` action

* [ ] lists events created by user, ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previously attended by user **using event model scope** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-09-04 22:56 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @AhmedTohamy01 and @ezeilo-su  :lollipop: :balloon: 

### Thank you for working on some of the changes requested by the previous reviewer :medal_sports: :medal_sports: I see your actions working in the console but we need to create pages as well so let's work on them :construction: :construction_worker: :construction_worker: 

## General
* [ ]  Lets kindly remove the `README` title in the readme.MD file.
> As the previous reviewer requested is better to have a meaningful protect name as the title instead of 'README'

* [ ]  Let define routes for each component in the app.
> you haven't define routes for the project yet after you create the views you should create routes in this file so it's possible to load them in the browser

![image](https://user-images.githubusercontent.com/52209067/92289424-ab6d6100-eecd-11ea-8fa5-0d61ef18e725.png)

* [ ]  The events table should have a creator_id as the foreign key ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> instead of having the default 'user_id' in your events table you should use 'creator_id' build the proper migrations and changes in the model to make it happen.

#### Behavior
> Just as it was requested by the previous user, the following views should exist and work using the browser.

* [ ]  It has functional `login` page (authentication WITHOUT password, just providing a user email) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ]  Logged in user can create new event  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ]  Event's index page displays past and upcoming events lists  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ]  The event's show page displays the list of attendants  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ]  The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ]  Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
 
#### Project specific
#### Database foreign keys and indexes ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/foreign_key_index_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
> These changes are still not reflected in your schema please build the proper migrations to achieve the following
* [ ]  the events table has column `creator_id` of type `integer`
* [ ]  an index for `creator_id` column is added
* [ ]  an index for `event_id` column is added
* [ ]  an index for `user_id` column is added

#### Tests
> Just as it was requested by the previous reviewer :pray: Kindly Install and use Rspec and capybara to test your project.
* [ ]  models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ]  authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ]  event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

### Comments made by the previous reviewer

- [ ] Address to the comments the previous reviewer made in your code.

### That's it team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-09-11 00:32 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Kindly read the previous reviews.
Take a look at the comment left below.

Once done, kindly submit a new code review request.

Thanks

Mael FOSSO

2020-09-11 00:32 UTC, maelfosso commented on README.md
> +# README
Change that title, please. Put the title of the project.

Please, All the previous reviewers mentioned it

2020-09-11 00:32 UTC, maelfosso commented on README.md
> +* How to run the test - Test should be run from CLI, by first starting the Rails server``` rails server ```or``` rails server ``` from the project director. Then, open a new terminal in the same proj
- `rails db:migrate` or `rails db:migrate`
- `rails server` or `rails server`

Two same command. Why?

2020-09-11 00:32 UTC, maelfosso commented on README.md
> +* Database creation - After cloning the project, navigate to the project directory (```cd Microverse-Private-Events```), then execute the following command``` rails db:migrate ```or``` rails db:migra
Please, complete it by adding `rails db:create` which come before `rails db:migrate`

2020-09-11 00:32 UTC, maelfosso commented on config/routes.rb
> +end
It's still empty.

Please, why did you implement it as asked by the previous reviewers?

2020-09-11 00:32 UTC, maelfosso commented on db/schema.rb
> +  end
Please, add indexes in that tables.
Add migrations for that.

2020-10-04 11:55 UTC, ezeilo-su commented
Can you kindly review again. All the required changes have been effected.
Thanks for your helpful feedback.

2020-10-04 13:03 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @AhmedTohamy01 and @ezeilo-su, great job in fixing some of the comments made by the previous TSE's :+1: I would however highlight some of them here so we can get it approved :slightly_smiling_face: 

- The README file has some repetitions, we have been asked to fix that but we still have them in the README file. Kindly take time and go through the README and get this fixed :+1: 
- I have problems with running `rails db:create` and `rails db:migrate`. These commands return the following error 
``` 
-- add_index(:events, :creator_id)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: main.events
/home/daniel/Desktop/code-reviews/Microverse-Private-Events/db/migrate/20200924185058_add_index_to_events_creator_id.rb:3:in `change' 
```
Kindly fix it.

Kindly submit another code review once these are addressed :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-10-04 16:02 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job fixing the README and the migrations :100: Awesome!!! However, after running `rails s` I got this error with webpack configuration. :fireworks: 
![fxx](https://user-images.githubusercontent.com/46388113/95020420-91ed3f80-065a-11eb-8090-5c45f5e3dae7.png)
Kindly address this error :+1: 

Once this is fixed, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-10-04 16:24 UTC, ezeilo-su commented
After running rails db:create and rails db:migrate, also run yarn add jquery@3.4.1 bootstrap@3.4.1 in the project directory to install both jQuery and Bootstrap’s JavaScript library in our application, for proper configuration of the asset pipeline. But if you continue getting the error with Webpacker, which the previous reviewer got, you can use the live demo version which you find here: https://sleepy-temple-36134.herokuapp.com

2020-10-04 16:42 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, congratulations on this project. :100: The project works perfectly on heroku live version :fireworks:  I hereby approve the project :smile: Congratulations
[Optional]
- Kindly fix the issue with webpack

Good luck with your next project :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-10-04 16:48 UTC, merged